Repository PrestaShopCorp/prestashop_accounts_vue_components, pull requests merged in 2020-12, with the labels that each got.

#46 CI/CD - Storybook
  .github/workflows/cd-prod-stable.yml
  .github/workflows/ci-cd-alpha.yml
  .github/workflows/ci-cd-stable.yml
  README.md
  cloud/backend.tf
  cloud/deployment_storybook.tf
  cloud/network.tf
  cloud/provider.tf
  cloud/remote_state.tf
  cloud/variables.tf
Labels: quality assurance needed

#45 Account - Add the possibility to unlink the shop through de vuejs component
  package.json
  src/components/PsAccounts.vue
  src/components/modal/Modal.vue
  src/components/panel/Account.vue
  src/locale/lang/en.json
  yarn.lock
Labels: ready for review

#47 Add a slot to the PsAccount Component and remove billing components from lib
  src/Intro.stories.mdx
  src/components/PsAccounts.stories.mdx
  src/components/PsAccounts.vue
  src/components/panel/Billing.stories.mdx
  src/components/panel/Billing.vue
  src/components/panel/Plans.vue
  src/lib/BillingValidator.js
  src/lib/ContextValidator.js
  src/locale/lang/de.json
  src/locale/lang/en.json
  src/locale/lang/es.json
  src/locale/lang/fr.json
  src/locale/lang/it.json
  src/locale/lang/nl.json
  src/locale/lang/pl.json
  src/locale/lang/pt.json
Labels: WIP
