Repository PrestaShopCorp/prestashop_accounts_vue_components, pull requests merged in 2021-11, with the labels that each got.

#92 Use Crowdin Github Integration instead of Github action
  .github/workflows/crowdin.yml
  crowdin.yml
Labels: ready for review

#115 Add a redirect_to query param to redirect the user to his BO on a fallback context
  src/components/crossdomains/LinkShopModal.vue
Labels: bug, enhancement, ready for review

#114 Handling shop domain error in Account component
  src/components/alert/ShopUrlShouldExists.vue
  src/components/panel/Account.vue
  src/components/panel/accountSubComponents/AccountLinkToUi.vue
  src/lib/ContextValidator.js
  src/locale/lang/en.json
Labels: fix

#117 Account 972: Add psaccounts version to context validator and component viewed tracking
  src/components/PsAccounts.vue
  src/full.js
  src/lib/ContextValidator.js
Labels: enhancement

#119 Handle case where PS EventBus is not enabled
  src/components/PsAccounts.vue
  src/components/alert/PsAccountComponentAlertDisplay.vue
  src/components/alert/subComponents/EventBusNotEnabled.stories.mdx
  src/components/alert/subComponents/EventBusNotEnabled.vue
  src/lib/context.js
  src/locale/lang/en.json
Labels: Feature

#129 New Crowdin updates
  src/locale/lang/de.json
  src/locale/lang/es.json
  src/locale/lang/fr.json
  src/locale/lang/it.json
  src/locale/lang/nl.json
  src/locale/lang/pl.json
  src/locale/lang/pt.json
Labels: translations
