Repository PrestaShopCorp/prestashop_accounts_vue_components, pull requests merged in 2022-05, with the labels that each got.

#156 New Crowdin updates
  src/locale/lang/fr.json
Labels: translations

#158 New Crowdin updates
  src/locales/de.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/it.json
  src/locales/nl.json
  src/locales/pl.json
  src/locales/pt.json
Labels: translations

#160 Fix: Change title h3 to p to avoid conflicts with global rules of prestakit
  src/components/panel/accountSubComponents/AccountHeader.vue
Labels: fix

#157 feat: remove ps_eventbus integration
  README.md
  src/composables/usePSAccountsContext.ts
  src/containers/PsAccountComponentAlertDisplay.vue
  src/i18n.ts
Labels: ready for review
